### ISSUE TITLE
Possible fatal error when using WordPress theme customizer

### ISSUE THREAD

**Issue by htmgarcia** [publishpress/PublishPress-Blocks#1384]
Pro version. Didn't tested under free version.

Error is not consistent
`Uncaught TypeError: in_array(): Argument #2 ($haystack) must be of type array, null given in /wp-content/plugins/advanced-gutenberg-pro/init.php:109 Stack trace: #0 /wp-content/plugins/advanced-gutenberg-pro/init.php(109): in_array('core/legacy-wid...', NULL) #1 /wp-includes/class-wp-hook.php(324): advg_check_legacy_widget_block_init('') #2 /wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array) #3 /wp-includes/plugin.php(517): WP_Hook->do_action(Array) #4 //wp-admin/admin.php(175): do_action('admin_init') #5 /wp-admin/customize.php(13): require_once('/www/httpslogti...') #6 {main} thrown`

**Comment by htmgarcia** [comment]
Imported slideshow and tried to reproduce in local with no luck
